### ISSUE TITLE
Error message: Couldn't find a tree builder

### ISSUE THREAD

**Issue by 01Andrea01** [DominikBuchner/BOLDigger2#1]
Dear Dominik,
thanks for the new version of bolddigger!!!

Fresh out of the installation did not work, but then I realized that it needed some updates.

After the Python updates it worked, at least until it started searching in BOLD... 

13:48:07: Trying to log in.
BOLD username:
BOLD password: 
13:48:16: Login successful.
13:48:16: Starting to gather download links from species level database.
Generating download links:   0%|                        | 0/572 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "/home/andrea/.local/bin/boldigger2", line 8, in <module>
    sys.exit(main())
  File "/home/andrea/.local/lib/python3.10/site-packages/boldigger2/__main__.py", line 44, in main
    id_engine_coi.main(arguments.fasta_file)
  File "/home/andrea/.local/lib/python3.10/site-packages/boldigger2/id_engine_coi.py", line 464, in main
    fasta_dict = gather_download_links(
  File "/home/andrea/.local/lib/python3.10/site-packages/boldigger2/id_engine_coi.py", line 129, in gather_download_links
    soup = BSoup(response.text, "html5lib")
  File "/home/andrea/.local/lib/python3.10/site-packages/bs4/__init__.py", line 250, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

The error points to something missing. I'm not a python expert and I just rely on google searches, but I couldn't find anything that solved the problem. It looks like html5lib is installed on my system:

sudo pip install html5lib
Requirement already satisfied: html5lib in /usr/lib/python3/dist-packages (1.0.1)

But then I don't know where the problem is.

Is it related to the package or to my system?

Any help is appreciated.

Best,
Andrea

**Comment by DominikBuchner** [comment]
Hi there,
Will fix this on Monday.
Best Dominik

01Andrea01 ***@***.***> schrieb am Do., 30. Mai 2024, 13:58:

**Comment by DominikBuchner** [comment]
Hi Andrea,
Can you please try "pip install --upgrade html5lib" and "pip install lxml"
and rerun boldigger2 and check if the error persists?

Which operating system are you on?

Dominik Buchner ***@***.***> schrieb am Do., 30. Mai
2024, 15:56:

**Comment by 01Andrea01** [comment]
Hi Dominik,

I'm working on Ubuntu 20.04

I managed to solve part of the issue. It seems that the problem was the python update. There is some issue with pip, as explained here: https://stackoverflow.com/questions/69503329/pip-is-not-working-for-python-3-10-on-ubuntu

I first upgraded python and pip using the following instructions:
https://gist.github.com/rutcreate/c0041e842f858ceb455b748809763ddb

but it turns out that using simply pip install doesn't work.

this is what worked for html5lib and lxml:

python3.10 -m pip install --upgrade html5lib
python3.10 -m pip install lxml_html_clean

However, now there is another issue:

08:12:36: Trying to log in.
BOLD username:
BOLD password: 
08:12:48: Login successful.
08:12:48: Starting to gather download links from species level database.
Generating download links:   0%|                        | 0/572 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "/home/biome-id/.local/lib/python3.10/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/biome-id/.local/bin/boldigger2", line 8, in <module>
    sys.exit(main())
  File "/home/biome-id/.local/lib/python3.10/site-packages/boldigger2/__main__.py", line 44, in main
    id_engine_coi.main(arguments.fasta_file)
  File "/home/biome-id/.local/lib/python3.10/site-packages/boldigger2/id_engine_coi.py", line 464, in main
    fasta_dict = gather_download_links(
  File "/home/biome-id/.local/lib/python3.10/site-packages/boldigger2/id_engine_coi.py", line 148, in gather_download_links
    with pd.HDFStore(
  File "/home/biome-id/.local/lib/python3.10/site-packages/pandas/io/pytables.py", line 566, in __init__
    tables = import_optional_dependency("tables")
  File "/home/biome-id/.local/lib/python3.10/site-packages/pandas/compat/_optional.py", line 138, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.

trying to install pytable with python3.10 -m pip install pytables doesn't work for me

andrea@andreasPC:~$ python3.10 -m pip install --upgrade pytables
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement pytables (from versions: none)
ERROR: No matching distribution found for pytables

My feeling is that the issue has something with the python upgrades...

**Comment by DominikBuchner** [comment]
Yes it's another dependency issue. Two options:
Either you directly install boldigger2 on the python 3.10 version:

python3.10 -m pip install boldigger2

Or you install the tables dependency:

Python3.10 -m pip install tables

01Andrea01 ***@***.***> schrieb am Fr., 31. Mai 2024, 08:20:

**Comment by DominikBuchner** [comment]
I'll add that to the readme for linux users.

Dominik Buchner ***@***.***> schrieb am Fr., 31. Mai
2024, 08:25:

**Comment by DominikBuchner** [comment]
If you opt for a reinstall you can also run boldigger2 with the specified
python version:

python3.10 -m boldigger2 identify fasta

Dominik Buchner ***@***.***> schrieb am Fr., 31. Mai
2024, 08:26:

**Comment by 01Andrea01** [comment]
I already had boldigger2 installed with the command:

python3.10 -m pip install boldigger2

Everything is working now. This did the trick:

python3.10 -m pip install tables

I am running the program using the standard command:

boldigger2 identify otus.fasta

If that doesn't work I'll let you know

Thanks for the help!!!

Andrea

**Comment by DominikBuchner** [comment]
Glad it worked, looking forward to feedback from my users :)

01Andrea01 ***@***.***> schrieb am Fr., 31. Mai 2024, 09:19:

**Comment by 01Andrea01** [comment]
next issue...

NotImplementedError: ':-soup-contains' pseudo-class is not implemented at this time
Downloading top 100 hits:   0%|                         | 0/572 [00:11<?, ?it/s]

I updated soupsieve with:

python3.10 -m pip install --upgrade soupsieve

the next step is running now, and the program is downloading top 100 species level record. I'll keep you posted.

Have to admit, it's way faster than boldigger gui and I personally prefer working on the command line.

**Comment by DominikBuchner** [comment]
Fixed with version 1.0.3.
