### ISSUE TITLE
Lower levels not assigned when an intermediate level is missing

### ISSUE THREAD

**Issue by naurasd** [DominikBuchner/BOLDigger2#13]
Hi,

I have the following COI sequence:

>ASV2
TCTAAGTCATATTACGAGCCACTCTGGTGGTGCAGTTGATTTAGCTATTTTCAGTTTACATTTATCTGGAGCGAGCAGTATTTTAGGGGCGATTAACTTTATTACCACTATCTTTAACATGCGTGGGCCTGGTCTGGGCTTCCATCGCTTACCTTTATTTGTGTGGTCTGTTCTGATTACGGCCTTCTTACTTCTTCTCTCTTTACCGGTTTTAGCGGGAGCGATTACGATGCTGTTAACGGATCGTAACTTCAATACCTCGTTCTTTGATCCGGCGGGCGGAGGTGACCCTATTTTGTTCCAGCACCTTTTT

It has two 100% similarity hits with published sequences of _Bathycoccus prasinos_. However, in the published records, there is no family level information. This results in BOLDIGGER2 giving classification only to order level for this ASV in the_identification_result.xlsx file, despite two 100% matches with species level records. Is this a bug or intended behaviour?

Thanks

Nauras

**Comment by DominikBuchner** [comment]
Hi Nauras,
I'll look into this in the next few days but I think this is connected to this:
https://github.com/DominikBuchner/BOLDigger2/issues/10
And therefore intended behaviour since I need a way to work with this incomplete taxonomy records. It should affect only a really minor part of all sequences in BOLD. If you have a better suggestion I'm open for it :)

**Comment by naurasd** [comment]
Thanks for the super quick reply!

But didnt you introduce the IncompleteTaxonomy flag? Why don't i get this flagged in my case? (i just get flag no. 1).

I am using 1.0.6, the latets version.

**Comment by DominikBuchner** [comment]
Bacause there are hits without Incomplete Taxonomy, which can be used. Incomplete taxonomy is only raised if ALL hits contain incomplete taxonomy and therefore after filtering nothing remains.

**Comment by naurasd** [comment]
Alright. but would it be possible to get this flag also if there are 100% hits with published records among the top 100 hits? or introduce a different flag?

even if it may not be a frequently occurring issue, i really dont want to lose any species level information in my data set, specifically seeing that getting taxonomic information for COI metabarcoding data is already challenging. 

if it is too complicated, thats the way it s of course ;-)

**Comment by DominikBuchner** [comment]
I'll think about our options here :)

**Comment by naurasd** [comment]
thank you ;-) 

have sent you an email, it would in general be helpful i think if the issues for the old boldigger packages are still being attended to, seeing that many of us still have the old packages as part of our pipelines. 

all the best :-D

**Comment by DominikBuchner** [comment]
Please see: https://github.com/DominikBuchner/BOLDigger3
