### ISSUE TITLE
Pandas requires tables 3.8.0 or newer

### ISSUE THREAD

**Issue by bwprice** [DominikBuchner/BOLDigger2#2]
OS windows 10.
error: "ImportError: Pandas requires version '3.8.0' or newer of 'tables' (version '3.7.0' currently installed)."
fix: upgrade tables using `pip install tables --upgrade`

**Comment by DominikBuchner** [comment]
Will fix all dependency issues on Monday, thanks Ben :)

Ben Price ***@***.***> schrieb am Sa., 1. Juni 2024, 14:04:

**Comment by DominikBuchner** [comment]
Fixed with version 1.0.3.
