### ISSUE TITLE
Index error

### ISSUE THREAD

**Issue by LiseKlunder** [DominikBuchner/BOLDigger2#20]
Hi Dominik, 
I get an error during the "downloading top 100 hits" at about 1/3 of the sequences (total of 55000 OTUs).
The error says: index error, list index out of range. Did you encounter this before? I guess I could try to split up the input fasta file and run the script multiple time, but maybe you know an easy solution. 
Thanks!

**Comment by DominikBuchner** [comment]
I encountered it yesterday for the first time, I got an idea what might be happening and I'm working on a fix atm. BOLD is quite unreliable at the moment :/

**Comment by DominikBuchner** [comment]
Can you upload the download links file?

**Comment by DominikBuchner** [comment]
Fixed with 2.0.0
