### ISSUE TITLE
Problem with Bold login after unstable internet connexion

### ISSUE THREAD

**Issue by bpostaire** [DominikBuchner/BOLDigger2#23]
Hello,
I cannot seem to log in with my Bold credentials anymore.
 They work fine on the Bold website, and your script worked perfectly last time I used it (1 month ago).
It also worked fine earlier today, but after several internet problems while it was running (unstable connection + Bold website unavailable for a few minutes), I cannot restart it.
Any idea what could be happening? (computer already turned off and on, just in case)
Thank you for your work!
Bautisse

**Comment by DominikBuchner** [comment]
Hi bautisse,
Due to the update to bold v5 im experiencing a lot of issues lately. Id
suggest waiting until tomorrow and retry. If it persists I'm happy to take
a look :)

bpostaire ***@***.***> schrieb am Di., 24. Sept. 2024, 19:38:

**Comment by bpostaire** [comment]
Hi Dominik,
No worries and thank you for your quick answer! I figured it could be related, but I thought maybe it was an issue with my computer.
I'll wait and see tomorrow, or later this week.
Thanks again,
Bautisse

**Comment by vanessamata** [comment]
I am having exactly the same issue. I have a big dataset (>2000 samples) with about 11,000 OTUs to go through and after several restarts with the connection being very slow, last night I stopped being able to login (but I am able to login on BOLD's website). It seems to persist this morning :(

**Comment by DominikBuchner** [comment]
Okay, sounds like sth I'll have to work on. I'll see what I can do. Please also expect a major update after October 1st, I assume that the BOLD v5 update will break the code.

**Comment by DominikBuchner** [comment]
Fixed with 2.2.1

**Comment by vanessamata** [comment]
Seems to be working now! thanks! :D Yes I expect that with BOLD v5 things will crash, which is exactly why I was trying to finish this before 1st October eheh
