### ISSUE TITLE
Unclosed file warning - Please close it before reopening

### ISSUE THREAD

**Issue by OndroV** [DominikBuchner/BOLDigger2#24]
Hi Dominik,

I ran into an UnclosedFileWarning saying that my 16000_top_100_hits.h5.lz is already opened, but in read-only mode (see below, [files uploaded to GoogleDrive due to size](https://drive.google.com/drive/folders/1hPPpgnPZdS-MbSHedRXCwNGhZKxurux7?usp=sharing)). This happened after I got a Windows bluescreen :D When the pc restarted I tried to resume boldigger and found out that the top hits are already downloaded, but I couldn't make it work further. Do you have any idea about how to fix it, please? 

I tried [opening and closing the file in python manually](https://stackoverflow.com/questions/56149237/do-i-need-to-manually-close-a-hdf5-file), got no errors there, but nothing changed for boldigger2.
I wonder if [something like this can be added to the code](https://github.com/pandas-dev/pandas/issues/19931#issuecomment-1845927033) to close the h5.lz files before opening?

Good luck with the BOLD update :) Cheers,
Ondrej

python3.12 -m boldigger2 identify -username XX -password XX 16000.fasta
13:31:59: Trying to log in.
13:32:03: Login successful.
13:32:07: Starting to download from the species level database.
13:32:07: Starting to download from the all records database.
13:32:07: Performing second login for requesting links from the all records database.
13:32:07: Trying to log in.
13:32:11: Login successful.
13:32:12: Starting to gather download links from the all records database.
13:32:14: All records top 100 records successfully downloaded.
13:32:14: Trying to order the top 100 hits.
13:32:18: Hits are already ordered from a previous run.
/home/ono/.local/lib/python3.12/site-packages/tables/group.py:1160: UserWarning: problems loading leaf ``/additional_data/table``::

  Internal error reading the elements (H5ARRAYOreadSlice returned errorcode -8)

The leaf will become an ``UnImplemented`` node.
  warnings.warn(
Downloading additional data:   0%|                                                           | 0/174 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ono/.local/lib/python3.12/site-packages/boldigger2/__main__.py", line 98, in <module>
    main()
  File "/home/ono/.local/lib/python3.12/site-packages/boldigger2/__main__.py", line 88, in main
    id_engine_coi.main(
  File "/home/ono/.local/lib/python3.12/site-packages/boldigger2/id_engine_coi.py", line 674, in main
    additional_data_download.main(fasta_path, hdf_name_top_100_hits, read_fasta)
  File "/home/ono/.local/lib/python3.12/site-packages/boldigger2/additional_data_download.py", line 439, in main
    download_data(process_ids_to_download, hdf_name_top_100_hits)
  File "/home/ono/.local/lib/python3.12/site-packages/boldigger2/additional_data_download.py", line 292, in download_data
    json_response_to_dataframe(
  File "/home/ono/.local/lib/python3.12/site-packages/boldigger2/additional_data_download.py", line 234, in json_response_to_dataframe
    with pd.HDFStore(
         ^^^^^^^^^^^^
  File "/home/ono/.local/lib/python3.12/site-packages/pandas/io/pytables.py", line 585, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/ono/.local/lib/python3.12/site-packages/pandas/io/pytables.py", line 745, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ono/.local/lib/python3.12/site-packages/tables/file.py", line 283, in open_file
    raise ValueError(
ValueError: The file '16000_top_100_hits.h5.lz' is already opened, but in read-only mode.  Please close it before reopening in append mode.
/home/ono/.local/lib/python3.12/site-packages/tables/file.py:113: UnclosedFileWarning: Closing remaining open file: 16000_top_100_hits.h5.lz
  warnings.warn(UnclosedFileWarning(msg))

**Comment by DominikBuchner** [comment]
Hi ondrej,
Blue screen does not seem to be something that needs a fix. Since the hdf
store is opened with a context manager it will automatically be closed once
written. I'll so if I can recover it

Ondrej Vargovčík ***@***.***> schrieb am So., 29. Sept. 2024,
14:01:

**Comment by DominikBuchner** [comment]
Hi Ondrej,

I restored your file, you will have to download the additional data again. Just name it like your "old" file and run BOLDigger2 again. The error should disappear.

best
Dominik

[16000_top_100_hits_restored.h5.zip](https://github.com/user-attachments/files/17179425/16000_top_100_hits_restored.h5.zip)

**Comment by OndroV** [comment]
Thank you so much! Sure, no fix expected for the blue screen itself, but perhaps there are options to make future BOLDigger2 versions work even after such accidents, or to guide the user how to restore the files themselves.

Best!
Ondrej

**Comment by DominikBuchner** [comment]
I'll implement a recovery for broken files after the update.
