### ISSUE TITLE
Could we be allowed to skip certain problematic sequences to avoid getting stuck?

### ISSUE THREAD

**Issue by OndroV** [DominikBuchner/BOLDigger2#25]
Hi Dominik,

I guess this is also related to the poor performance before BOLD update, but solving it might be helpful for the future:
BOLDigger is finished for many sequences, but there is a single sequence among them that stuck the process during `Downloading additional data:   0%|  | 0/1` only giving messages like  `Malformed response. Switching proxy.` or `No proxy available, waiting` or `Read timed out, retrying`. The loop stops with SSLError or ConnectionError from time to time.

Is there a way to overcome this? Or perhaps in future versions could the user be offered a choice to continue without downloading additional data for such problematic sequences / situations? Because now all the results are unavailable only due to the single sequence :D It happened to me in four datasets lately (sharing through [Google Drive](https://drive.google.com/drive/folders/1TfFobPj9h0XQisne0iBRvQ0eT6KJOZ0u?usp=sharing) again due to size limit).

Best,
Ondrej

08:23:03: Trying to log in.
08:23:05: Login successful.
08:23:08: Starting to download from the species level database.
08:23:08: Starting to download from the all records database.
08:23:08: Performing second login for requesting links from the all records database.
08:23:08: Trying to log in.
08:23:10: Login successful.
08:23:12: Starting to gather download links from the all records database.
08:23:12: All records top 100 records successfully downloaded.
08:23:12: Trying to order the top 100 hits.
08:23:15: Hits are already ordered from a previous run.
08:23:16: Malformed response. Switching proxy.
... and the loop that I described

**Comment by DominikBuchner** [comment]
I expect this to go away with the update and the new BOLD API.. the old API just seems to be broken in this regard, returning incomplete records. If not I will think of a workaround. For now, removal of this specific sequence from the fasta should solve the issue.

**Comment by OndroV** [comment]
Great! A dumb question, but quick google didnt help me to view the h5.lz files: Would you please share how to identify which sequence is causing the trouble? :D
Thanks so much!
Ondrej

**Comment by DominikBuchner** [comment]
With python 
```
import pandas as pd

data = pd.read_hdf(YOUR_FILE, key = "top_100_hits_sorted")
print(data["ID"].unique())
```

Should give you all IDs in your hdf storage, sorted in input order. You then have to compare that with your fasta and identify the sequence that causes trouble :)

**Comment by OndroV** [comment]
Thank you Dominik. Unfortunately, I still wasn't able to identify the problem. All the 1000 sequences from fasta are present among the `data["ID"].unique()`. Also, all Process_IDs from the `key="top_100_hits_sorted"` are present in the `key="additional_data"`. 

Interestingly, I found a few empty lines throughout the additional_data. It seemed suspicious, because the few successful boldigger runs that I quickly checked didn't have any empty line there. But 1 of the 4 datasets that are stuck in this loop was OK in this regard (no empty lines).

**Comment by DominikBuchner** [comment]
Okay, this is strange. I assume that the API does not return valid data for those IDs. Can this wait for after the BOLD update?

**Comment by OndroV** [comment]
Sure, I was planning to work on another project first anyway. Then maybe in 1-2 weeks I'd try again with these problematic datasets. Thank you very much and fingers crossed!

**Comment by OndroV** [comment]
Hi, my problem was solved by rerunning boldigger2 for the problematic datasets, so feel free to close the issue. Still, it would be nice if future boldigger versions could skip such sequences, finish the job for the rest of the dataset and then rerun only the individual problematic sequences. 

Btw if anyone struggles with additional data download these days, I recommend a quick edit of the file additional_data_download.py this way :

Locate the file in your system:
$ python3.12
>>> import inspect
>>> import boldigger2
>>> inspect.getfile(boldigger2)

'/home/ono/.local/lib/python3.12/site-packages/boldigger2/__init__.py'

>>> quit()

Edit the http:// into https:// within the link in line 147: "https://www.boldsystems.org/index.php/API_Public/specimen?ids={}&format=json"
(e.g. by opening the file manually using the nano command-line text editor and then use Ctrl+W to find first occurrence of "http"):
$ nano /home/ono/.local/lib/python3.12/site-packages/boldigger2/additional_data_download.py

Best,
Ondrej

**Comment by OndroV** [comment]
OK, seems that they finally rolled the new website out. Right in the middle of my additional data download process :D Would be great if it's possible to finish the process on v4. 
I figured out that the links in additional_data_download.py and login.py must be changed to v4.boldsystems.org, but I am currently getting malformed responses and wonder if there is another quick solution that I missed. Perhaps the http in proxy - don't know if it's possible to make it https :D

**Comment by DominikBuchner** [comment]
Okay, the API of BOLD v4 has been taken down, so now way to make it work for v4. At the moment, also the ID engine of v5 is unavailable, I'm wondering what the hell is happening over in Canada :D Will keep you updated, will take me a few days.

**Comment by OndroV** [comment]
Thank you so much! Looking forward, fingers crossed. 
+I attach a few feedback notes that I made lately and might be useful in the current upgrade (also going back to some [features suggested earlier](https://github.com/DominikBuchner/BOLDigger/issues/33#issuecomment-2015197561)). From CESAMIR conference I remember that Arne and @TillMacher mentioned some future tool to facilitate easier revision of the obtained BOLD identifications, but I guess that is beyond the current window of opportunity :) 

[BOLDigger2_feedback.pdf](https://github.com/user-attachments/files/17487457/BOLDigger2_feedback.pdf)

**Comment by DominikBuchner** [comment]
Please see: https://github.com/DominikBuchner/BOLDigger3
