### ISSUE TITLE
Unable to login using BOLD credentials

### ISSUE THREAD

**Issue by JordanBeas** [DominikBuchner/BOLDigger2#26]
Hi Dominik! 
For a couple of weeks I have been unable to use BOLDigger, on entering my bold credentials I get the unable to log in, check your username and password message but I can use them to login to BOLD online. Is this to do with the disruption due to BOLD5 updates?
Thanks for your help and thank you for BOLDigger it's great! :)
Jordan

**Comment by OndroV** [comment]
Hi Jordan, do you use the latest version? I guess some login issues were solved [lately](https://github.com/DominikBuchner/BOLDigger2/issues/23#issuecomment-2373515868)
Ondrej

**Comment by JordanBeas** [comment]
Hi! Yes I updated my version, I was hoping that would fix it but it's still having trouble so I wondered if it was a BOLD problem...even the website has been super glitchy recently

**Comment by DominikBuchner** [comment]
Hi Jordan,

Im on vacation until October 20th. Will take a look into this right
afterwards. Sorry for the inconvenience, the update is killing me -.-

Jordan Beasley ***@***.***> schrieb am Do., 10. Okt. 2024,
13:42:

**Comment by JordanBeas** [comment]
Hi Dominik! No worries at all, don't worry about it I'll hold on until BOLD5! Enjoy your vacation, no work allowed on holidays!! :)

**Comment by OndroV** [comment]
Strange - for me it works pretty well and I have it running throughout this week. Not as fast as during summer, but much better than last week. From time to time it crashes or has to repeat login, but it can always continue in my case. As just another user, I can only recommend to try with another account in the meantime. 
Fingers crossed Jordan and enjoy the holiday Dominik :)

**Comment by JordanBeas** [comment]
Thank you Ondrej! It's suddenly working again! No idea what happened but it must have been a problem my end!
Thank you for your help!
:)

**Comment by naurasd** [comment]
Having the problem that within the same run, I am able to login, and then suddenly it says I am unable to login and that I am supposed to check username and password. See below:

```
17:44:55: Trying to log in.
17:44:57: Login successful.
17:45:00: Starting to download from the species level database.
17:45:00: Starting to download from the all records database.
17:45:00: Performing second login for requesting links from the all records data
base.
17:45:00: Trying to log in.
17:45:02: Login successful.
17:45:04: Starting to gather download links from the all records database.
17:50:05: BOLD did not respond. Keeping query size at 5.
17:55:06: BOLD did not respond. Keeping query size at 5.
18:00:06: BOLD did not respond. Keeping query size at 5.
18:05:07: BOLD did not respond. Keeping query size at 5.
18:10:07: BOLD did not respond. Keeping query size at 5.
18:15:08: BOLD did not respond. Keeping query size at 5.
18:20:09: BOLD did not respond. Keeping query size at 5.
18:25:10: BOLD did not respond. Keeping query size at 5.
18:26:57: BOLD did not return a sufficient number of download links. Retrying
18:29:57: Trying to log in.
18:38:37: Unable to log in.
Please check username and password.
```

Is this more of an issue of BOLD not responding?

**Comment by DominikBuchner** [comment]
Bold update is today, the url bold systems.org will lead to a different
webpage soon, this will break boldigger. Am already working on a fix but
will take some time. I expect everything to be way faster after the update
so in the long run it will be great. Please have some patience with me,
doing my best.

naurasd ***@***.***> schrieb am Mo., 21. Okt. 2024, 18:43:

**Comment by naurasd** [comment]
no worries, you are doing a great job! we appreciate it!

**Comment by DominikBuchner** [comment]
Good evening,
the new ID engine is really nice and today I already came quite far, so just a quick update:
The id engine is already working again, tomorrow I'll focus on the additional data and the top hit selection. I'm hoping to be able to publish BOLDigger3 next week. So far the speed upgrade looks quite promising and I'm looking to integrate all databases and all operating modes offered by BOLD :) :

![image](https://github.com/user-attachments/assets/6f53c7ab-d87f-4096-b321-6462e8acc272)

**Comment by DominikBuchner** [comment]
Please see: https://github.com/DominikBuchner/BOLDigger3

**Comment by myoung02** [comment]
Using the new BOLDigger 3, but I'm still very sad at the loss of BOLDigger and BOLDigger2... and possibility these packages might be updated to access the v4.boldsystems.org site/databases?

Thank you so much for all your work on this project - it has made my life immensely easier in the world of metabarcoding!

**Comment by DominikBuchner** [comment]
Hi there,
unfortunately, I do not have the time to maintain both of them, and since BOLDv4 will be shut down at some point in the (near) future, I believe it is not worth the effort. The API is no longer working anyways, so I cannot access additional data with BD2 or BD1, so I'd basically have to rewrite all the code to pull the additional data from BOLD v5. 

What I already thought about: Maybe I'll do something like "BOLDigger-Offline" where you can download the full database and then blast with whatever parameters you like. But this is something more like for the 2nd half of 2025.
