### ISSUE TITLE
Error when login in

### ISSUE THREAD

**Issue by francielleholtz** [DominikBuchner/BOLDigger2#27]
Hello,

I am trying to login in, but I keep getting this error: 
<img width="1004" alt="Screenshot 2024-11-06 at 17 56 56" src="https://github.com/user-attachments/assets/66f9c48a-2bd9-4828-b237-67e4e2dccbf6">

It was working just find a couple of weeks ago. My info is right as I have login in on the web page with the same credentials. What should I do?

Thank you :)

**Comment by DominikBuchner** [comment]
Hi Francielle, 
BOLD has been updated to v5 breaking boldigger2. 
Please see: https://github.com/DominikBuchner/BOLDigger3
A login is no longer required :)
