### ISSUE TITLE
Allow adjusting taxonomic similarity thresholds

### ISSUE THREAD

**Issue by hjarnek** [DominikBuchner/BOLDigger2#3]
Hi, and thank you very much for this great update of BOLDigger!

It's amazing how simple it is to use now. There is only one argument that I'm missing, and that is the ability to adjust the default taxonomic similarity thresholds (97%: species level, 95%: genus level, 90%: family level, 85%: order level, <85%: class level). For a start, the 97% species threshold is outdated for most taxa, and there are various notions of what is right for the other levels. Could you consider adding this feature?

**Comment by DominikBuchner** [comment]
Will add this in a future update as an optional argument in case you don't want to use the defaults.
best
Dominik

**Comment by DominikBuchner** [comment]
fixed with version 1.0.7. Let me know how it works for you :) See readme for details.
