### ISSUE TITLE
Automated login/username and password input

### ISSUE THREAD

**Issue by SchistoDan** [DominikBuchner/BOLDigger2#5]
Hi Dominik,

First off, thanks for making a brilliant and easy to use tool! 

Some colleagues and I are interested in incorporating BOLDigger2 into a pipeline as a barcode validation step. Is it currently possible to automate input of the login credentials, such as by providing a config file or including them when running BOLDigger identify (as I think you could in Boldigger-cline)? 

Best,
Dan

**Comment by DominikBuchner** [comment]
Hi Dan,
will add this feature in the future. However, it poses a security risk, with your userdata floating around unencrypted. If you need a temporary solution, you can just replace lines 12 and 13 of login.py in your installation with your credentials :)

best
Dominik

**Comment by DominikBuchner** [comment]
Hi Dan,
I just pushed v 1.0.5 and integrated this as an optional argument. Please update your boldigger2 installation, then you can run:
`boldigger2 identify PATH_TO_FASTA -username USERNAME -password PASSWORD`
To bypass the login request.  
Let me know how it works for you. If you omit those optional arguments BOLDigger2 will ask for your credentials as before.

best
Dominik

**Comment by SchistoDan** [comment]
Hi Dominik,

Thanks for so quickly integrating that feature! I've updated to the new version and have run the COI test data - all ran fine and looks good.

Thanks again,
Dan
